//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GearStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
        [DisplayName("Mã hoá đơn")]
        public int OrderID { get; set; }
        [DisplayName("Mã KH")]
        public int CustomerID { get; set; }
        [DisplayName("Ngày đặt hàng")]
        public Nullable<System.DateTime> OrderDate { get; set; }
        [DisplayName("Ngày gửi hàng")]
        public Nullable<System.DateTime> ShippedDate { get; set; }
        [DisplayName("Tình trạng")]
        public bool Status { get; set; }
        [DisplayName("Đã gửi")]
        public bool IsShipped { get; set; }
        [DisplayName("Đã thanh toán")]
        public bool IsPaid { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
