//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GearStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
        [DisplayName("Mã sản phẩm")]
        public int ProductID { get; set; }
        [DisplayName("Tên sản phẩm")]
        public string ProductName { get; set; }
        [DisplayName("Thể loại")]
        public int CategoryID { get; set; }
        [DisplayName("Hãng SX")]
        public int ManufacturerID { get; set; }
        [DisplayName("Giá")]
        public decimal Price { get; set; }
        [DisplayName("Ảnh")]
        public string PhotoFilePatch { get; set; }
        [DisplayName("Số lượng trong kho")]
        public int UnitsInStock { get; set; }
        [DisplayName("Ngày cập nhật")]
        public System.DateTime UpdatedDate { get; set; }
        [DisplayName("Reorder Level")]
        public int ReorderLevel { get; set; }
        [DisplayName("Rating")]
        public byte Rating { get; set; }
        [DisplayName("Dừng bán")]
        public bool Discontinued { get; set; }
        [DisplayName("Chi tiết")]
        public string Details { get; set; }
        [DisplayName("Mô tả")]
        public string Description { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
